/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "primary-container": "#e07a5f",
        "inverse-primary": "#ffb4a1",
        "surface": "#ffffff",
        "surface-variant": "#dfe0ff",
        "surface-bright": "#fbf8ff",
        "on-tertiary-container": "#402b00",
        "on-secondary-container": "#3d6c57",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#ffb4a1",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#3c0800",
        "tertiary-fixed": "#ffdeab",
        "on-surface": "#161a32",
        "outline": "#88726d",
        "on-primary-container": "#5b1604",
        "secondary": "#386753",
        "on-tertiary": "#ffffff",
        "tertiary": "#765a28",
        "tertiary-fixed-dim": "#e6c185",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "secondary-fixed": "#bbeed4",
        "on-background": "#161a32",
        "secondary-container": "#b8ebd1",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e6ff",
        "on-surface-variant": "#55423e",
        "inverse-on-surface": "#f1efff",
        "secondary-fixed-dim": "#9fd1b8",
        "surface-dim": "#d6d8f9",
        "outline-variant": "#dbc1ba",
        "surface-container-low": "#f4f2ff",
        "on-tertiary-fixed": "#271900",
        "inverse-surface": "#2b2e48",
        "on-secondary-fixed-variant": "#1f4f3c",
        "surface-tint": "#9a442d",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#7c2e19",
        "on-tertiary-fixed-variant": "#5c4212",
        "tertiary-container": "#b3915a",
        "background": "#F4EFE6",
        "surface-container": "#edecff",
        "surface-container-highest": "#dfe0ff",
        "on-secondary-fixed": "#002115",
        "primary-fixed": "#ffdbd2",
        "primary": "#E07A5F",
        "soft-blue": "#4A90E2"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "8px",
        "max-width-content": "1200px",
        "md": "24px",
        "sm": "12px",
        "gutter": "16px",
        "xl": "64px",
        "lg": "40px",
        "margin-mobile": "20px",
        "margin-desktop": "auto",
        "xs": "4px"
      },
      "maxWidth": {
        "xs": "20rem",
        "sm": "24rem",
        "md": "28rem",
        "lg": "32rem",
        "xl": "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem",
        "content": "1200px"
      },
      "fontFamily": {
        "chord-display": ["Nunito Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Nunito Sans", "sans-serif"],
        "headline-md": ["Nunito Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Nunito Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"]
      },
      "fontSize": {
        "chord-display": ["48px", { "lineHeight": "52px", "fontWeight": "900" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "38px", "fontWeight": "800" }],
        "headline-md": ["28px", { "lineHeight": "34px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      },
      "boxShadow": {
        'card': '0 8px 20px -4px rgba(22, 26, 50, 0.08)',
        'card-hover': '0 4px 12px -2px rgba(22, 26, 50, 0.04)',
      }
    },
  },
  plugins: [],
}
